version: '3.9'

services:
    app:
        build: ./library_back/.
        container_name: library
        restart: always
        ports:
            - 8000:8000
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/library_back/code
        depends_on:
            - database

    database:
        image: postgres
        container_name: library_db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=library_db
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata: