version: '3.7'

services:
    database:
        image: postgres
        container_name: library_db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=library_db
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local