name: CI
on:
    push:
        branches: [ main ]

env: 
    POSTGRES_DB: library_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: database
    POSTGRES_PORT: 5432

jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build app
              run: docker-compose -f ./docker-compose.yml up --build -d
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: docker-compose -f ./docker-compose.yml up --build -d
            - name: Make migrations
              run: docker exec library python manage.py makemigrations && docker exec library python manage.py migrate
            - name: Test
              run: docker exec library python manage.py test
    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: docker-compose -f ./docker-compose.yml up --build -d
            - name: Lint Front
              run: docker exec library_app npx eslint src --quiet --ext ".js" --fix
            - name: Lint Back
              run: docker exec library flake8 src/ accounts/ books/ --exit-zero